[TD-13307]<docs>: add description to docs index.
taosdata/TDengine pull request #10065
Opened 2022-01-27 03:11 UTC by sangshuduo

2022-01-27 03:21 UTC, changxiaoqiang requested changes

2022-01-27 03:21 UTC, changxiaoqiang commented on documentation20/cn/00.index/docs.md
> +* taosdump: TDengine 数据备份工具。[用户手册](taosdum://github.com/taosdata/taos-tools/blob/develop/taosdump-user-manual-CN.md)
Please check the url, it is not correct.

2022-01-27 03:44 UTC, changxiaoqiang approved these changes
LGTM

2022-01-27 15:37 UTC, merged

2022-01-27 16:43 UTC, jtao1735 commented on documentation20/cn/00.index/docs.md
> +* taosAdapter: TDengine 集群和应用之间的 RESTful 接口适配服务。[用户手册](/tools/adapter)
能否把用户手册的链接放在左边的taosAdapter, taosBenchmark, taosDump，TDinsight等上面？而不是显式的加上“用户手册”这样的字，要与其他部分风格一致才行

2022-01-29 16:36 UTC, sangshuduo commented on documentation20/cn/00.index/docs.md
> +* taosAdapter: TDengine 集群和应用之间的 RESTful 接口适配服务。[用户手册](/tools/adapter)
done