Add php connector
taosdata/TDengine pull request #10891
Opened 2022-03-22 04:08 UTC by Yurunsoft

2022-03-22 05:29 UTC, sangshuduo commented
Thanks for your contribution. Would you like to add your connector as a submodule of TDengine?

2022-03-22 05:57 UTC, Yurunsoft commented
No problem.
If necessary, I can also transfer the project to taosdata.

2022-03-22 07:29 UTC, sangshuduo commented
> No problem. If necessary, I can also transfer the project to taosdata.

I notice you use the Apache license. I don't know if the PHP team would encourage the connector to use GPL as you might know the TDengine use AGPL。

2022-03-22 07:34 UTC, sangshuduo commented
BTW, would you like to add a few test cases into `TDengine/tests` to make the CI check if PHP is not broken after someone submit new code?

2022-03-22 08:15 UTC, Yurunsoft commented
OK, I'll change license later and add tests

I'll close this PR first and reopen it after it's finished

2022-03-31 06:54 UTC, Yurunsoft commented
I have changed PHP tdengine license to AGPLv3.

I don't know how to add test cases and debugging. The Ci of tdengine doesn't seem to run in GitHub actions

2022-03-31 07:31 UTC, sangshuduo commented
> I have changed php-tdengine license to AGPLv3.
> 
> I don't know how to add test cases and debugging. The CI of tdengine doesn't seem to run in GitHub actions

Please add your test case and document how to run it. We will take care of them to add to our CI.

2022-03-31 07:34 UTC, sangshuduo commented on .gitmodules
> +[submodule "src/connector/tdengine-restful-connector"]
I think tdengine-restful-connector is a general name that might confuse the user. I suggest using a name with 'php' to be more indicative like another one you submitted.

2022-03-31 07:34 UTC, sangshuduo requested changes
a few comments

2022-03-31 08:59 UTC, sangshuduo approved these changes
LGTM

2022-04-06 04:51 UTC, merged