[TD-14316]<docs>: add jdbc 2.0.38 doc
taosdata/TDengine pull request #11261
Opened 2022-04-06 09:56 UTC by huolibo

2022-04-06 10:57 UTC, dingbo8128 approved these changes
LGTM

2022-04-06 16:34 UTC, sangshuduo commented on documentation20/en/08.connector/01.java/docs.md
> +| 2.0.38                  | X                        | X                        | 2.4.0.12 以上            | 1.8.x       |
Chinese in English document

2022-04-06 16:35 UTC, sangshuduo commented on documentation20/en/08.connector/01.java/docs.md
> +Starting with version taos-jdbcdriver-2.0.38 and TDengine 2.4.0.12, **JDBC-RESTful** support batch load function. Data is transmitted between TAOS-JDBcDriver and TDengine through WebSocket connection
official feature name is bulk pulling

2022-04-06 16:46 UTC, sangshuduo commented on documentation20/en/08.connector/01.java/docs.md
> +Starting with version taos-jdbcdriver-2.0.38 and TDengine 2.4.0.12, **JDBC-RESTful** support batch load function. Data is transmitted between TAOS-JDBcDriver and TDengine through WebSocket connection
My version:
JDBC 2.0.38 and later version with TDengine 2.4.0.12 (and later version) start to support a new bulk-pulling feature. It provides higher data transmission performance and larger volume data queries capability via WebSocket communication.

2022-04-06 16:48 UTC, sangshuduo commented on documentation20/cn/08.connector/01.java/docs.md
> +properties.setProperty(TSDBDriver.PROPERTY_KEY_BATCH_LOAD, "true");
the official feature name is bulk pulling. what is batch load?

2022-04-06 16:53 UTC, sangshuduo requested changes
see my comments

2022-04-07 04:00 UTC, sangshuduo requested changes
see my comments

2022-04-07 04:00 UTC, sangshuduo commented on documentation20/en/08.connector/01.java/docs.md
> +| 2.0.38                  | X                        | X                        | 2.4.0.12 and above       | 1.8.x       |
and later is an idiom.

https://english.stackexchange.com/questions/112257/above-or-later-when-referencing-a-range-of-versions-of-software

2022-04-07 07:30 UTC, sangshuduo approved these changes
LGTM

2022-04-07 07:30 UTC, merged