docs: clear settings about RESTful api
taosdata/TDengine pull request #11495
Opened 2022-04-14 08:44 UTC by dingbo8128

2022-04-14 08:51 UTC, huskar-t approved these changes
LGTM

2022-04-14 09:03 UTC, sangshuduo requested changes
see my comments

2022-04-14 09:03 UTC, sangshuduo commented on docs-cn/14-reference/02-restful-api/02-restful-api.mdx
> +下面仅列出一些与 RESTful 接口有关的配置参数，其他系统参数请看配置文件里的说明。
TDengine 2.3 和之后的版本默认使用 taosAdaper 提供的 RESTful 服务, 请参考 taosAdaper [对应的配置方法](https://github.com/taosdata/taosadapter/blob/develop/README-CN.md#%E5%A6%82%E4%BD%95%E4%BB%8E%E6%97%A7%E7%89%88%E6%9C%AC-tdengine-%E8%BF%81%E7%A7%BB%E5%88%B0-taosadapter)。在更早的 TDengine 中使用 taosd 内置 RESTful 服务, 配置需要写在 taosd 的配置文件 taos.cfg 中。下面仅列出一些与内置 RESTful 服务有关的配置参数，其他系统参数请看配置文件里的说明。

2022-04-14 09:03 UTC, sangshuduo commented on docs-cn/14-reference/02-restful-api/02-restful-api.mdx
> +如果使用 taosd 提供的 RESTful API, 那么以上配置需要写在 taosd 的配置文件 taos.cfg 中。如果使用 taosAdaper 提供的 RESTful API, 那么需要参考 taosAdaper [对应的配置方法](https://github.com/taosdata/taosadapter/blob/develop/README-CN.md#%E5%A6%82%
这一段就不需要了

2022-04-15 10:59 UTC, merged

2022-04-15 10:59 UTC, dingbo8128 commented on docs-cn/14-reference/02-restful-api/02-restful-api.mdx
> +如果使用 taosd 提供的 RESTful API, 那么以上配置需要写在 taosd 的配置文件 taos.cfg 中。如果使用 taosAdaper 提供的 RESTful API, 那么需要参考 taosAdaper [对应的配置方法](https://github.com/taosdata/taosadapter/blob/develop/README-CN.md#%E5%A6%82%
ok