docs: change document of jdbc connector
taosdata/TDengine pull request #11682
Opened 2022-04-20 10:17 UTC by huolibo

2022-04-20 10:36 UTC, dingbo8128 commented on docs-cn/14-reference/03-connector/java.mdx
> +#### 指定 URL 和 Properties 获取连接
前面是三级标题， 这里是四级标题，意思是这里是针对 RESTful 链接的吗？

2022-04-20 10:38 UTC, dingbo8128 commented on docs-cn/14-reference/03-connector/java.mdx
> +- TSDBDriver.PROPERTY_KEY_PASSWORD：用户登录密码，默认值 'taosdata'。
这些参数哪些是 本地连接支持的，哪些是 RESTful 连接支持的， 需要说明一下。

2022-04-20 10:40 UTC, dingbo8128 commented on docs-cn/14-reference/03-connector/java.mdx
>  ## 常见问题
没有 API 参考。

2022-04-20 11:09 UTC, huolibo commented on docs-cn/14-reference/03-connector/java.mdx
>  ## 常见问题
没有doc链接

2022-04-20 11:09 UTC, huolibo commented on docs-cn/14-reference/03-connector/java.mdx
> +- TSDBDriver.PROPERTY_KEY_PASSWORD：用户登录密码，默认值 'taosdata'。
本地连接和restful下面的参数是区分的

2022-04-20 11:10 UTC, sangshuduo requested changes
commented offline

2022-04-20 11:10 UTC, huolibo commented on docs-cn/14-reference/03-connector/java.mdx
> +#### 指定 URL 和 Properties 获取连接
可以设置为三级标题，只是感觉和 本地连接 、restful 不太搭配。

2022-04-22 08:58 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/java.mdx
> +`taos-jdbcdriver` 的实现包括两种形式： JDBC 本地连接和 JDBC-RESTful（taos-jdbcdriver-2.0.18 开始支持 JDBC-RESTful）。 JDBC 本地连接通过调用客户端驱动 libtaos.so（或 taos.dll ）的本地方法实现， JDBC-RESTful 则在内部封装了 RESTful 接口实现。
支持两种连接方式：JDBC 本地连接和 JDBC-REST 连接

2022-04-22 09:00 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/java.mdx
> +`taos-jdbcdriver` 的实现包括两种形式： JDBC 本地连接和 JDBC-RESTful（taos-jdbcdriver-2.0.18 开始支持 JDBC-RESTful）。 JDBC 本地连接通过调用客户端驱动 libtaos.so（或 taos.dll ）的本地方法实现， JDBC-RESTful 则在内部封装了 RESTful 接口实现。
JDBC-RESTful 则通过 TDengine REST 接口建立连接，REST 连接实现的功能集合和本地连接有少量不同。

2022-04-22 09:04 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/java.mdx
> +4. TDengine-client（使用 JDBC 本地连接时必须，使用 JDBC-RESTful 时非必须）
已安装 Java 1.8 以上运行环境
已安装 maven 3.6 以上版本
以安装 TDengine client （使用 JDBC 本地连接必须安装，使用 JDBC-REST 无需安装）

2022-04-22 09:06 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/java.mdx
> +**注意**：在 Windows 环境开发时需要安装 TDengine 对应的 [Windows 客户端](https://www.taosdata.com/cn/all-downloads/#TDengine-Windows-Client)，Linux 服务器安装完 TDengine 之后默认已安装 client，也可以单独安装 [Linux 客户端](/get-started/) 连接远程
**注意**：在 Windows 环境开发时需要安装 TDengine 对应的 [Windows 客户端](https://www.taosdata.com/cn/all-downloads/#TDengine-Windows-Client)。TDengine Linux 服务端安装包也附带了 TDengine client，也可以单独安装 [Linux 客户端](/get-started/) 连接远端 TDengine 集群。

2022-04-22 09:06 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/java.mdx
>  可以通过下载 TDengine 的源码，自己编译最新版本的 java connector
Java connector

2022-04-22 09:08 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/java.mdx
> +- batchErrorIgnore：true：在执行 Statement 的 executeBatch 时，如果中间有一条 SQL 执行失败，继续执行下面的 SQL 了。false：不再执行失败 SQL 后的任何语句。默认值为：false。
batchErrorIgnore：true：在执行 Statement 的 executeBatch 时，如果中间有一条 SQL 执行失败将继续执行下面的 SQL 。false：不再执行失败 SQL 后的任何语句。默认值为：false。

2022-04-22 09:09 UTC, sangshuduo requested changes
see my comments

2022-04-22 09:34 UTC, sangshuduo approved these changes
LGTM

2022-04-22 09:40 UTC, dingbo8128 commented on docs-cn/14-reference/03-connector/java.mdx
> +### 使用源码编译安装
【源码编译安装】 更简洁

2022-04-22 09:46 UTC, dingbo8128 commented on docs-cn/14-reference/03-connector/java.mdx
> +编译后，在 target 目录下会产生 taos-jdbcdriver-2.0.XX-dist.jar 的 jar 包，并自动将此 jar 文件放在 maven 本地仓库中。
哪个 target 目录？
前面半句称为 jar 包， 后面也称 jar 包就行。 
maven  本地仓库放的也是 dist.jar 吗？ 是不带 dist 的jar 吧？

2022-04-22 09:52 UTC, dingbo8128 approved these changes

2022-04-22 10:42 UTC, merged