docs:refine C# reference without api reference
taosdata/TDengine pull request #11701
Opened 2022-04-21 02:41 UTC by xleili

2022-04-22 04:47 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +C# connector 目前是通过 TDengine 客户端驱动建立本地连接。但是对于RESTful连接并未进行暂未封装，需要用户参考 [RESTful APIs](https://docs.taosdata.com//reference/restful-api/) 自己封装。
并未进行暂未封装

2022-04-22 04:48 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +C# connector 目前是通过 TDengine 客户端驱动建立本地连接。但是对于RESTful连接并未进行暂未封装，需要用户参考 [RESTful APIs](https://docs.taosdata.com//reference/restful-api/) 自己封装。
目前是通过 => 目前支持

2022-04-22 04:49 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +C# 连接器支持的系统有：Linux 64/Windows x64/Windows x86
可以不必强调 64 位？

2022-04-22 04:49 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +|        1.0.2       | TDever-2.5.0.x,ver-2.4.0.x,ver-2.3.4+ | 连接管理、同步查询、错误信息   |
TDever?

2022-04-22 04:49 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +### RESTful 连接
前面提过这里是否不必再提？

2022-04-22 04:51 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +**注意**：由于 TDengine 的应用驱动是使用 C 语言开发的，使用 C# 驱动包时需要依赖系统对应的本地函数库。
本地函数库 => 客户端驱动

2022-04-22 04:51 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +**注意**：在 Windows 环境开发时需要安装 TDengine 对应的 [windows 客户端](https://www.taosdata.com/cn/all-downloads/#TDengine-Windows-Client)，Linux 服务器安装完 TDengine 之后默认已安装 client，也可以单独安装 [Linux 客户端](/get-started/) 连接远程
Windows

2022-04-22 05:01 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +## 重要更新记录（optional）
don't mention "optional"

2022-04-22 05:02 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +* java.lang.UnsatisfiedLinkError: no taos in java.library.path 原因：程序没有找到依赖的本地函数库 taos。 解决方法：Windows 下可以将 C:\TDengine\driver\taos.dll 拷贝到 C:\Windows\System32\ 目录下，Linux 下将建立如下软链 ln -s /usr/local/taos/
why mention JAVA in C# connector?

2022-04-22 05:02 UTC, sangshuduo requested changes
see my comments

2022-04-22 09:37 UTC, xleili commented on docs-cn/14-reference/03-connector/csharp.mdx
> +C# 连接器支持的系统有：Linux 64/Windows x64/Windows x86
没在非64位系统是验证过。还是写的保守一点吧。

2022-04-22 10:14 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +通过阅读本文可以了解如何在 Windows 或者 Linx 环境中安装 TDengine C# connector，以及如何连接 TDengine 数据库、查询数据、插入数据等基本操作。
Linx => Linux

2022-04-22 10:15 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +但是对于 RESTful 连接暂未封装，需要用户参考 [RESTful APIs](https://docs.taosdata.com//reference/restful-api/) 自己封装。
建议：

目前暂未封装 RESTful 接口，用户可以参考 [RESTful APIs](https://docs.taosdata.com//reference/restful-api/) 文档自行编写。

2022-04-22 10:16 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +C# 连接器支持的系统有：Linux 64/Windows x64/Windows x86
格式和其他连接器保持一致

2022-04-22 10:16 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +|        1.0.6       | v2.5.0.x,v2.4.0.x,v2.3.4+ | 修复schemaless |
修复 schemaless

2022-04-22 10:17 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +|        1.0.2       | v2.5.0.x,v2.4.0.x,v2.3.4+ | 支持连接管理、同步查询、错误信息   |
支持连接管理、同步查询、错误信息等功能

2022-04-22 10:17 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +|        1.0.3       | v2.5.0.x,v2.4.0.x,v2.3.4+ | 支持参数绑定、schemaless, json tag |
。。。等功能

2022-04-22 10:17 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +|        1.0.4       | v2.5.0.x,v2.4.0.x,v2.3.4+ | 支持异步查询，订阅、修复绑定参数     |
。。。等功能

2022-04-22 10:18 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +|        1.0.5       | v2.5.0.x,v2.4.0.x,v2.3.4+ | 修复 Windows 同步查询中文报错   |
。。。bug

2022-04-22 10:18 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +"本地连接" 指连接器通过本地的客户端驱动程序 taosc 直接与服务端程序 taosd 建立连接。
中文正文中应该用中文全家标点符号

2022-04-22 10:19 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +5. 获取系统信息（暂不支持）
暂不支持和标题。。支持的。。矛盾，应该去掉

2022-04-22 10:21 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +**注意**：由于 TDengine 的应用驱动是使用 C 语言开发的，使用 C# 驱动包时需要依赖系统对应的客户端驱动。
修改未：
**注意**：使用 C# 连接器包时需要安装对应的客户端驱动。

2022-04-22 10:26 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +* 其它问题请参考 [Issues](https://github.com/taosdata/TDengine/issues)
这里是不是应该跳到 FAQ ？

2022-04-22 10:27 UTC, sangshuduo requested changes
see my comments

2022-04-22 12:05 UTC, xleili commented on docs-cn/14-reference/03-connector/csharp.mdx
> +C# 连接器支持的系统有：Linux 64/Windows x64/Windows x86
等出模板，再改。

2022-04-23 11:35 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +## 版本支持
这段其实是 changelog

2022-04-23 11:36 UTC, sangshuduo commented on docs-cn/14-reference/03-connector/csharp.mdx
> +|        1.0.6       | v2.5.0.x,v2.4.0.x,v2.3.4+ | 修复schemaless bug。|
是不是 2.3.4+ 就包含所有版本了？

2022-04-23 11:39 UTC, sangshuduo approved these changes
LGTM with comments. will modify late to align with all connectors

2022-04-23 11:39 UTC, merged