docs: add description for how subtable name is generated
taosdata/TDengine pull request #14114
Opened 2022-06-22 08:22 UTC by xiaopingcs

2022-06-22 08:42 UTC, dingbo8128 commented on docs/zh/14-reference/13-schemaless/13-schemaless.md
> +子表名具体实现规则可以参考：[子表名生成规则代码实现](https://github.com/taosdata/TDengine/blob/06e05dfdf9c394e8ad5dd2ad4a54de53ea4e93f5/src/client/src/tscParseLineProtocol.c#L153-L188)。
documentation should be more readable than code,  if not, we should improve the description in documentation instead of refering code

2022-06-22 08:45 UTC, dingbo8128 requested changes
documentation should be more readable than code, if not, we should improve the description in documentation instead of refering code

2022-07-29 05:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/taosdata/TDengine?pullRequest=14114) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/taosdata/TDengine?pullRequest=14114) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/taosdata/TDengine?pullRequest=14114) it.</sub>

2022-08-01 12:42 UTC, xiaopingcs commented
> documentation should be more readable than code, if not, we should improve the description in documentation instead of refering code

Done

2022-08-01 12:43 UTC, xiaopingcs commented
Please review @dingbo8128 @gccgdb1234

2022-08-02 09:59 UTC, gccgdb1234 commented on docs/en/14-reference/13-schemaless/13-schemaless.md
> +> - Encrypt above string with MD5 to folling string: "68e766edd3747cdeec5a96caeaed7721"
folling -> following ？

2022-08-02 10:06 UTC, xiaopingcs commented on docs/en/14-reference/13-schemaless/13-schemaless.md
> +> - Encrypt above string with MD5 to folling string: "68e766edd3747cdeec5a96caeaed7721"
fixed

2022-08-02 10:18 UTC, merged