fix:window time wait
taosdata/TDengine pull request #18613
Opened 2022-12-01 08:10 UTC by facetosea

2022-12-01 08:41 UTC, sangshuduo requested changes

2022-12-01 08:41 UTC, sangshuduo commented on source/os/src/osSemaphore.c
>    ts.tv_nsec += ms * 1000000;
should not pass compile here

2022-12-01 12:15 UTC, sangshuduo approved these changes
LGTM

2022-12-02 00:01 UTC, guanshengliang approved these changes

2022-12-02 00:01 UTC, merged