add TDengine Cloud PrivateLink Help
taosdata/TDengine pull request #21493
Opened 2023-05-26 06:34 UTC by sheyanjie-qq

2023-06-25 10:28 UTC, feici02 requested changes

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +PrivateLink is a highly available, scalable technology that you can use to privately connect your VPC to TDengine service as if they were in one VPC. PrivateLink to allow the resources in your VPC to
```suggestion
PrivateLink is a highly available, scalable technology that you can use to privately connect your VPC to TDengine service as if they were in one VPC. PrivateLink allows the resources in your VPC to connect to TDengine service using your private IP addresses, and does not expose your data to the public internet.
```

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +Currently, TDengine Cloud only supports private endpoint connections in AWS. Other clouds similar to GCP or Azure will soon be supported.
```suggestion
Currently, TDengine Cloud only supports private endpoint connections in AWS. Other clouds such as GCP or Azure will soon be supported.
```

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +For more detailed of the PrivateLink concept, please see the following AWS documents:
```suggestion
For more details of the PrivateLink concept, please see the following AWS documents:  
```

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +1. Open [Network](https://console.cloud.tdengine.com/instances) page in TDengine Cloud, Click **Service List** button.
```suggestion
1. Open [Network](https://console.cloud.tdengine.com/network) page in TDengine Cloud, Click **Service List** button.
```

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +1. In TDengine Cloud left navigation pane, select **Network**, then choose the **PrivateLink** tab, click **Create Connection** in the upper-right corner. The **Create Connection** page is displayed.
```suggestion
1. In TDengine Cloud left navigation pane, select **Network**, then choose the **PrivateLink** tab, click **Add New Private Link** in the upper-right corner. The **Add New Private Link** page will be displayed.
```

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +2. Firstly, set your preferred connection name, select the correct endpoint service to use to create the connection, and then enter the **VPC endpoint ID** you created in step 2.
```suggestion
2. Firstly, set your preferred connection name, select the correct endpoint service to use to create the connection, and then enter the **Endpoint ID** you created in step 2.
```

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +4. Click the **Confirm** button to create the private endpoint connection.
```suggestion
4. Click the **Add** button to create the private endpoint connection.
```

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +3. Click the **Validate** button to verify if the request existed and could be accepted.
```suggestion
3. Click the **Verify** button to verify if the request existed and could be accepted. 
```

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +1. Click the endpoint id link in **Endpoints** page you created in AWS the Step 2.
```suggestion
1. Click the endpoint id link in **Endpoints** page you created Step 2 on AWS.
```

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +Now you can access TDengine Cloud service in your VPC using the private DNS name. You can find the **private URL** in the [Instance page](https://console.cloud.tdengine.com/instances) in TDengine Clo
```suggestion
Now you can access TDengine Cloud service in your VPC using the private DNS name. You can find the **Private URL** in the [Instances page](https://console.cloud.tdengine.com/instances) in TDengine Cloud.
```

2023-06-25 10:28 UTC, feici02 commented on docs/en/14-network/private-link/index.md
> +1. Disconnect the connection in **endpoint connection list** page in TDengine Cloud. Wait the connection status to be DISCONNECTED.
```suggestion
1. Click the Action button in **endpoint connection list** page in TDengine Cloud. After a while, the connection status will be changed into DISCONNECTED.
```

2023-06-30 01:41 UTC, wingwing2005 approved these changes

2023-06-30 01:41 UTC, merged