Docs/ts 4883 3.0：Modify the taosBenchmark documentation for the TS-4883 problem
taosdata/TDengine pull request #26553
Opened 2024-07-12 12:44 UTC by YamingPei

Floating-point precision enhancement factor, which takes effect only when the data type is float/double. It has a valid range of positive integers from 1 to 1,000,000. It is used to enhance the precision of generated floating-point numbers, particularly when the min or max values are small. This property enhances the precision after the decimal point by powers of 10: scalingFactor of 10 indicates an enhancement of 1 decimal precision, 100 indicates an enhancement of 2 decimal precision, and so on.

2024-07-27 07:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/taosdata/TDengine?pullRequest=26553) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/taosdata/TDengine?pullRequest=26553) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/taosdata/TDengine?pullRequest=26553) it.</sub>

2024-07-29 09:12 UTC, feici02 requested changes

2024-07-29 09:12 UTC, feici02 commented on docs/zh/14-reference/05-taosbenchmark.md
> +- **max** : 浮点数精度增强因子，仅当数据类型是float/double时生效，有效值范围为1至1000000的正整数。用于增强生成浮点数的精度，特别是在min或max值较小的情况下。此属性按10的幂次增强小数点后的精度：scalingFactor为10表示增强1位小数精度，100表示增强2位，依此类推。
```suggestion
- **scalingFactor** : 浮点数精度增强因子，仅当数据类型是float/double时生效，有效值范围为1至1000000的正整数。用于增强生成浮点数的精度，特别是在min或max值较小的情况下。此属性按10的幂次增强小数点后的精度：scalingFactor为10表示增强1位小数精度，100表示增强2位，依此类推。
```

2024-07-29 09:15 UTC, feici02 approved these changes
LGTM

2024-10-30 10:49 UTC, guanshengliang approved these changes

2024-10-30 10:49 UTC, merged