Fix/TD-31587
taosdata/TDengine pull request #27649
Opened 2024-09-03 08:51 UTC by xiao-77

2024-09-03 09:54 UTC, cadem requested changes

2024-09-03 09:54 UTC, cadem commented on source/dnode/mgmt/node_mgmt/src/dmMonitor.c
> +  dTrace("send monitor report to %s:%u", tsMonitorFqdn, tsMonitorPort);
这个日志输出的描述不对

2024-09-03 09:54 UTC, cadem commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +  (void)taosThreadRwlockWrlock(&pMgmt->lock);
这里为什么是写锁?

2024-09-03 09:54 UTC, cadem commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +      r = taos_counter_delete(tsInsertCounter, keys[i]);
这个返回值返回到上层，上层也是加了void，还不如在这里打印日志，把函数返回值改为void

2024-09-03 09:54 UTC, cadem commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +  taos_counter_get_vgroup_ids(tsInsertCounter, &keys, &vgroup_ids);
返回值判断

2024-09-03 09:54 UTC, cadem commented on source/libs/monitorfw/src/taos_counter.c
> +  *vgroup_ids = (int32_t *)taos_malloc(key_list->size * sizeof(int32_t));
返回值判断

2024-09-03 09:54 UTC, cadem commented on source/libs/monitorfw/src/taos_counter.c
> +  *keys = (char **)taos_malloc(key_list->size * sizeof(char *));
返回值判断

2024-09-03 09:54 UTC, cadem commented on source/libs/monitorfw/src/taos_counter.c
> +  for (taos_linked_list_node_t *current_key = key_list->head; current_key != NULL; current_key = current_key->next) {
这里是否要加锁处理，不加锁是不是会有内存问题

2024-09-03 09:54 UTC, cadem commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +  for (int i = 0; i < list_size; i++) {
list_size在咱们这个场景下这么没问题，但是更好的方法是从taos_counter_get_vgroup_ids方法中传出来

2024-09-03 12:13 UTC, xiao-77 commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +      r = taos_counter_delete(tsInsertCounter, keys[i]);
这部分的日志，我看到日志要求上需要写上 req_id。请教下东明，对于监控模块的代码，这个日志应该怎么写？

2024-09-05 02:59 UTC, cadem commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +      r = taos_counter_delete(tsInsertCounter, keys[i]);
不用打印reqid

2024-09-05 03:09 UTC, cadem commented on source/libs/monitorfw/src/taos_counter.c
> +  *list_size = key_list->size;
这个操作要放在所保护里面

2024-09-05 03:13 UTC, xiao-77 commented on source/libs/monitorfw/src/taos_counter.c
> +  *list_size = key_list->size;
好的 已经修改了

2024-09-05 05:47 UTC, cadem approved these changes

2024-09-05 09:18 UTC, merged