doc/TD-32681-drop-dnode
taosdata/TDengine pull request #28511
Opened 2024-10-25 08:49 UTC by cadem

2024-10-25 09:44 UTC, hzcheng requested changes

2024-10-25 09:44 UTC, hzcheng commented on docs/en/14-reference/03-taos-sql/21-node.md
> +DROP DNODE dnode_id force
force 和 unsafe 应该是可选项，请用 [] 括起来，并补充一下指定与不指定的区别。

2024-10-25 09:44 UTC, hzcheng commented on docs/en/14-reference/03-taos-sql/21-node.md
> +DROP DNODE dnode_id unsafe
unsafe 同上。

2024-10-25 09:44 UTC, hzcheng commented on docs/zh/14-reference/03-taos-sql/21-node.md
> +DROP DNODE dnode_id force
同英文版。

2024-10-25 09:44 UTC, hzcheng commented on docs/zh/14-reference/03-taos-sql/21-node.md
> +DROP DNODE dnode_id unsafe
同英文版。

2024-10-25 09:53 UTC, hzcheng approved these changes

2024-10-26 09:06 UTC, guanshengliang approved these changes

2024-10-26 09:07 UTC, merged