Fix: alter wal level from 0 to 1or2 and restart failed
taosdata/TDengine pull request #28688
Opened 2024-11-07 09:45 UTC by xiao-77

2024-11-12 09:09 UTC, hzcheng requested changes

2024-11-12 09:09 UTC, hzcheng commented on source/libs/wal/src/walMgmt.c
> +    TAOS_RETURN(terrno);
增加错误日志

2024-11-12 09:09 UTC, hzcheng commented on source/libs/wal/src/walMgmt.c
> +    TAOS_RETURN(terrno);
1. 增加错误日志
2. 释放前面分配的资源

2024-11-12 09:09 UTC, hzcheng commented on source/libs/wal/src/walMgmt.c
> +    TAOS_RETURN(TSDB_CODE_FAILED);
1. 增加错误日志
2. 是否在这里释放前面分配的资源
3. 是否应该 return terrno。

2024-11-12 09:33 UTC, xiao-77 commented on source/libs/wal/src/walMgmt.c
> +    TAOS_RETURN(TSDB_CODE_FAILED);
谢谢提醒，已经修改，顺便看了下 wal 模块存在很多类似问题(文件打开后未关闭)，建立了一个 jira https://jira.taosdata.com:18080/browse/TD-32870 来跟踪，之后会将 wal 模块的类似问题一起修复。

2024-11-12 09:34 UTC, xiao-77 commented on source/libs/wal/src/walMgmt.c
> +    TAOS_RETURN(TSDB_CODE_FAILED);
谢谢提醒，已经修改。发现wal模块包含很多类似问题，已经建立jira，后续会提pr修改。

2024-11-12 09:36 UTC, stephenkgu commented on source/libs/wal/src/walMgmt.c
> +  TdFilePtr pIdxTFile, pLogTFile;
指针需要初始化下？

2024-11-12 09:45 UTC, xiao-77 commented on source/libs/wal/src/walMgmt.c
> +  TdFilePtr pIdxTFile, pLogTFile;
是的，已经修改。

2024-11-12 10:49 UTC, stephenkgu approved these changes

2024-11-13 06:01 UTC, guanshengliang approved these changes

2024-11-13 06:01 UTC, merged