Enh/useSafySysFunc
taosdata/TDengine pull request #29038
Opened 2024-12-04 05:36 UTC by yihaoDeng

# Description

Please briefly describe the code changes in this pull request.

# Checklist

Please check the items in the checklist if applicable.

- [ ] Is the user manual updated?
- [ ] Are the test cases passed and automated?
- [ ] Is there no significant decrease in test coverage?

2024-12-06 09:37 UTC, kailixu commented on source/dnode/mgmt/node_mgmt/src/dmMgmt.c
> +void                 dmClearVars(SDnode *pDnode) {
这格式看着不对齐。 在 222 行加个空行，再格式化一下，会比较整齐。

2024-12-06 09:54 UTC, kailixu commented on source/dnode/mnode/impl/src/mndDnode.c
> +      mError("dnode:%d, failed to get cfg since code: %s", pMCfgReq->dnodeId, tstrerror(code));
since code: %s， 后边跟的是错误信息，不是 code。

2024-12-06 09:54 UTC, kailixu commented on source/dnode/mnode/impl/src/mndDnode.c
> +      mError("dnode:%d, failed to get cfg since code: %s", pMCfgReq->dnodeId, tstrerror(code));
since code: %s， 后边跟的是错误信息，不是 code。

2024-12-06 10:19 UTC, kailixu commented on source/dnode/mnode/impl/src/mndMain.c
> +      tstrncpy(cfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
tstrncpy 会将 ENCRYPT_KEY_LEN - 1 置 0，与 strncpy 的语义不同了，应改为 ENCRYPT_KEY_LEN + 1。

2024-12-06 10:39 UTC, kailixu commented on source/util/src/tconfig.c
> +  code = taosStr2int32(primary, &cfg.primary);
这几处，level, primary, disable 有可能为 NULL，例如，dataDir /path。虽然，从效果上看，参数为 NULL 时 taoStr2Int32 会返回错误，会置为对应的 0，1，0 等值，与 均为 NULL 时返回值一样，但是还是有点区别。举个例子，用户配置了 dataDir /path0 a b c。 使用原来的 API，会返回 0 0 0，使用新 API 后，会返回 0 1 0， 都不是期望的报错退出，并给出提示。

2024-12-06 11:12 UTC, kailixu commented on source/os/src/osString.c
>    if (errno == ERANGE && (ret == LLONG_MAX || ret == LLONG_MIN)) {
对这个函数的实现之前的实现感觉很奇怪。直接判断 errno 就可以了，也不用管是 ERANGE/EINVAL，在  ERANGE 时 以加上了 ret 的判断， 在 EINVAL 时，还要判断 ret == 0。 在你这次加上 errno = 0 后，直接判断 errno 和 endptr == str 感觉就够了吧？

2024-12-06 11:17 UTC, kailixu commented on source/libs/wal/src/walWrite.c
> +    tstrncpy((char *)opts.key, pWal->cfg.encryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN 应该为 ENCRYPT_KEY_LEN + 1

2024-12-06 12:43 UTC, yihaoDeng commented on source/dnode/mgmt/node_mgmt/src/dmMgmt.c
> +void                 dmClearVars(SDnode *pDnode) {
done

2024-12-06 12:43 UTC, yihaoDeng commented on source/dnode/mnode/impl/src/mndDnode.c
> +      mError("dnode:%d, failed to get cfg since code: %s", pMCfgReq->dnodeId, tstrerror(code));
done

2024-12-06 12:44 UTC, yihaoDeng commented on source/dnode/mnode/impl/src/mndDnode.c
> +      mError("dnode:%d, failed to get cfg since code: %s", pMCfgReq->dnodeId, tstrerror(code));
done

2024-12-06 12:44 UTC, yihaoDeng commented on source/dnode/mnode/impl/src/mndMain.c
> +      tstrncpy(cfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
done

2024-12-06 12:45 UTC, yihaoDeng commented on source/libs/wal/src/walWrite.c
> +    tstrncpy((char *)opts.key, pWal->cfg.encryptKey, ENCRYPT_KEY_LEN);
done

2024-12-06 12:53 UTC, yihaoDeng commented on source/dnode/mnode/impl/src/mndMain.c
> +      tstrncpy(cfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
这个ENCRYPT_KEY_LEN挺有意思的，使用的好几处定义还不一样，有些定义的是：ENCRYPT_KEY_LEN+1,有些是ENCRYPT_KEY_LEN, 也不知道到底这个宏里面有没有'\0'的长度

2024-12-06 13:23 UTC, yihaoDeng commented on source/os/src/osString.c
>    if (errno == ERANGE && (ret == LLONG_MAX || ret == LLONG_MIN)) {
其实也不奇怪，这个函数要能转换各类情况，"1000x", "19:xx","","0x12G", 可以做测试实时，只判断errno, endstr==str好像是不够

2024-12-06 13:38 UTC, yihaoDeng commented on source/os/src/osString.c
>    if (errno == ERANGE && (ret == LLONG_MAX || ret == LLONG_MIN)) {
我就加了一点判断，可能是跨平台的问题，不过这个函数确实有点判断太冗余，我先改改，看是不是有跨平台的问题

2024-12-06 13:42 UTC, yihaoDeng commented on source/util/src/tconfig.c
> +  code = taosStr2int32(primary, &cfg.primary);
前后都不是符合预期的？ 那我先按你说的改

2024-12-09 05:51 UTC, kailixu requested changes

2024-12-09 05:51 UTC, kailixu commented on source/libs/tdb/src/db/tdbPager.c
> +      tstrncpy(opts.key, encryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN 应该为 ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/libs/tdb/src/db/tdbPager.c
> +          tstrncpy(opts.key, encryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN 应该为 ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/libs/tdb/src/db/tdbDb.c
> +    tstrncpy(pDb->encryptKey, encryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN 应该为 ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/libs/sync/src/syncMain.c
> +  tstrncpy(outToken, pSyncNode->arbToken, TSDB_ARB_TOKEN_SIZE);
这里原来的实现可能会有问题，outToken 长度只有 TSDB_ARB_TOKEN_SIZE，而不是 TSDB_ARB_TOKEN_SIZE + 1，strncpy 的行为是不确定的。不知道，为什么没有出错，除非 arbToken 都小于 TSDB_ARB_TOKEN_SIZE。

2024-12-09 05:51 UTC, kailixu commented on source/libs/stream/src/streamBackendRocksdb.c
> +  if (nBytes >= cap) {
taosMemoryFree(pChkpDir);

2024-12-09 05:51 UTC, kailixu commented on source/dnode/vnode/src/vnd/vnodeCfg.c
> +      tstrncpy(pCfg->tsdbCfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/vnode/src/vnd/vnodeCfg.c
> +      tstrncpy(pCfg->walCfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/vnode/src/vnd/vnodeCfg.c
> +      tstrncpy(pCfg->tdbEncryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/vnode/src/tsdb/tsdbReaderWriter.c
> +      tstrncpy(opts.key, encryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/vnode/src/tsdb/tsdbReaderWriter.c
> +        tstrncpy(opts.key, encryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/mnode/sdb/src/sdbFile.c
> +          tstrncpy(opts.key, tsEncryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/mnode/sdb/src/sdbFile.c
> +      tstrncpy(opts.key, tsEncryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/mgmt/node_util/src/dmFile.c
> +  tstrncpy(opts.key, key, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/mgmt/node_util/src/dmFile.c
> +  tstrncpy(opts.key, key, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/mgmt/node_util/src/dmFile.c
> +  tstrncpy(tsEncryptKey, encryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +    tstrncpy(pCfg->tdbEncryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +    tstrncpy(pCfg->walCfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +    tstrncpy(pCfg->tsdbCfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
ENCRYPT_KEY_LEN + 1

2024-12-09 05:51 UTC, kailixu commented on source/dnode/mnode/impl/src/mndUser.c
> +    tstrncpy(userObj.pass, pCreate->pass, TSDB_PASSWORD_LEN);
1. 在这里， userObj.pass 的大小为 TSDB_PASSWORD_LEN，按照strncpy 的方式，pass 就不以 0 结尾了。看了下判断用户是否一致的代码：`strncmp(connReq.passwd, pUser->pass, TSDB_PASSWORD_LEN - 1)`,  只比较 TSDB_PASSWORD_LEN - 1，实际上，用 memcmp 更加精确。 2. 虽然改为 tstrncpy，在功能上看起来不会有影响，但是，pass 的原始值最后一个 bit 有可能被改为 0 了，说不定后续哪里会出不可预知的问题。使用 memcpy 的方式保留原始值更加保险一些，并且，原来在处理 passwd 拷贝时，也都采用的 memcpy。

2024-12-09 06:04 UTC, yihaoDeng commented on source/dnode/mnode/impl/src/mndUser.c
> +    tstrncpy(userObj.pass, pCreate->pass, TSDB_PASSWORD_LEN);
done

2024-12-09 06:14 UTC, yihaoDeng commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +    tstrncpy(pCfg->tsdbCfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
reset

2024-12-09 06:15 UTC, yihaoDeng commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +    tstrncpy(pCfg->tdbEncryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
reset

2024-12-09 06:15 UTC, yihaoDeng commented on source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
> +    tstrncpy(pCfg->walCfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
reset

2024-12-09 06:16 UTC, yihaoDeng commented on source/dnode/mgmt/node_util/src/dmFile.c
> +  tstrncpy(tsEncryptKey, encryptKey, ENCRYPT_KEY_LEN);
reset

2024-12-09 06:16 UTC, yihaoDeng commented on source/dnode/mgmt/node_util/src/dmFile.c
> +  tstrncpy(opts.key, key, ENCRYPT_KEY_LEN);
reset

2024-12-09 06:16 UTC, yihaoDeng commented on source/dnode/vnode/src/vnd/vnodeCfg.c
> +      tstrncpy(pCfg->tdbEncryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
reset

2024-12-09 06:18 UTC, yihaoDeng commented on source/dnode/mnode/sdb/src/sdbFile.c
> +      tstrncpy(opts.key, tsEncryptKey, ENCRYPT_KEY_LEN);
done

2024-12-09 06:18 UTC, yihaoDeng commented on source/dnode/vnode/src/tsdb/tsdbReaderWriter.c
> +        tstrncpy(opts.key, encryptKey, ENCRYPT_KEY_LEN);
done

2024-12-09 06:21 UTC, yihaoDeng commented on source/dnode/vnode/src/vnd/vnodeCfg.c
> +      tstrncpy(pCfg->walCfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
done

2024-12-09 06:26 UTC, yihaoDeng commented on source/libs/tdb/src/db/tdbPager.c
> +          tstrncpy(opts.key, encryptKey, ENCRYPT_KEY_LEN);
done

2024-12-09 06:26 UTC, yihaoDeng commented on source/libs/tdb/src/db/tdbDb.c
> +    tstrncpy(pDb->encryptKey, encryptKey, ENCRYPT_KEY_LEN);
done

2024-12-09 06:29 UTC, yihaoDeng commented on source/libs/sync/src/syncMain.c
> +  tstrncpy(outToken, pSyncNode->arbToken, TSDB_ARB_TOKEN_SIZE);
reset

2024-12-09 06:29 UTC, yihaoDeng commented on source/libs/tdb/src/db/tdbPager.c
> +      tstrncpy(opts.key, encryptKey, ENCRYPT_KEY_LEN);
done

2024-12-09 06:32 UTC, yihaoDeng commented on source/dnode/vnode/src/vnd/vnodeCfg.c
> +      tstrncpy(pCfg->tsdbCfg.encryptKey, tsEncryptKey, ENCRYPT_KEY_LEN);
done

2024-12-09 06:46 UTC, yihaoDeng commented on source/dnode/mgmt/node_util/src/dmFile.c
> +  tstrncpy(opts.key, key, ENCRYPT_KEY_LEN);
done

2024-12-09 06:47 UTC, yihaoDeng commented on source/dnode/mnode/sdb/src/sdbFile.c
> +          tstrncpy(opts.key, tsEncryptKey, ENCRYPT_KEY_LEN);
done

2024-12-11 11:33 UTC, guanshengliang approved these changes

2024-12-11 11:47 UTC, merged