Docs :   python connector support SuperSet  product document
taosdata/TDengine pull request #29068
Opened 2024-12-09 06:51 UTC by DuanKuanJun

# Description

Please briefly describe the code changes in this pull request.

# Checklist

Please check the items in the checklist if applicable.

- [ ] Is the user manual updated?
- [ ] Are the test cases passed and automated?
- [ ] Is there no significant decrease in test coverage?

2024-12-12 09:55 UTC, sheyanjie-qq approved these changes

2024-12-14 04:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/taosdata/TDengine?pullRequest=29068) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/taosdata/TDengine?pullRequest=29068) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/taosdata/TDengine?pullRequest=29068) it.</sub>

2024-12-16 09:58 UTC, zitsen requested changes

2024-12-16 09:58 UTC, zitsen commented on docs/en/10-third-party/05-bi/11-superset.md
> +|:---------- |:---------------------------------------------------------   |
居中对齐使用：
```markdown
|:-----:|:-------:|
```

2024-12-16 10:03 UTC, DuanKuanJun commented on docs/en/10-third-party/05-bi/11-superset.md
> +|:---------- |:---------------------------------------------------------   |
想实现标题居中，内容左对齐，这样看着舒服，但 md 不支持这样的对齐功能，只能填充空格来达到这个效果

2024-12-16 10:21 UTC, DuanKuanJun commented on docs/en/10-third-party/05-bi/11-superset.md
> +|:---------- |:---------------------------------------------------------   |
使用 zitsen 推荐的 <center> </center> 解决

2024-12-17 01:21 UTC, zitsen approved these changes

2024-12-17 01:21 UTC, merged