improve the readme document with building steps
taosdata/TDengine pull request #3299
Opened 2020-08-31 01:49 UTC by goldeagle

improve building steps with specific linux distributions

2020-08-31 08:19 UTC, sangshuduo requested changes
Please remove gitee relative part since it's not maintained by us. Thanks.

2020-08-31 09:11 UTC, sangshuduo approved these changes

2020-09-01 00:17 UTC, goldeagle commented
ci failed? but why -_-||

2020-09-01 01:23 UTC, sangshuduo commented
CI passed now.

2020-09-01 01:40 UTC, guanshengliang approved these changes

2020-09-01 01:41 UTC, merged