init hivemq extension
taosdata/TDengine pull request #3750
Opened 2020-10-05 09:08 UTC by coldljy

implement HiveMQ extension

2020-10-06 03:46 UTC, sangshuduo commented
感谢提交PR，我们会在挑战赛截止日后进行评选

2020-10-10 06:27 UTC, sangshuduo commented
@coldljy 能否提供一个简要的文档说明？最好有英文版本。谢谢！

2020-10-13 13:39 UTC, coldljy commented
> @coldljy 能否提供一个简要的文档说明？最好有英文版本。谢谢！

有个 README.md，英文的 README.adoc

2020-10-19 14:49 UTC, sangshuduo requested changes
需要以 submodule 方式提交到 src/connector 目录下

2020-10-20 09:41 UTC, coldljy commented
> 需要以 submodule 方式提交到 src/connector 目录下

已移动至该目录

2020-10-21 02:49 UTC, sangshuduo commented
不是文件移过去，是需要你用一个 repo 包含代码，在 TDengine repo 中以 git submodule add 方式加进来，再提交 PR

2020-10-22 03:28 UTC, sangshuduo commented
请问是不是没有支持 RESTFul？抱歉这样不符合我们的要求。https://www.taosdata.com/blog/2020/09/07/1801.html

非常感谢参加本次竞赛。

2020-10-22 03:28 UTC, closed without merging