[TD-4228]<fix>: fix install error when grafana submodule not ready
taosdata/TDengine pull request #6151
Opened 2021-05-18 02:43 UTC by zitsen

2021-05-18 05:25 UTC, sangshuduo commented on packaging/deb/makedeb.sh
> +if [ -d "${top_dir}/src/connector/grafanaplugin/dist" ]; then
it may hide potential mistake if the submodule not updated

2021-05-18 05:26 UTC, sangshuduo requested changes
the user who build package should take care all submodule be updated. otherwise the process should be terminated with a clear error msg.

2021-05-18 06:11 UTC, zitsen commented on packaging/deb/makedeb.sh
> +if [ -d "${top_dir}/src/connector/grafanaplugin/dist" ]; then
Added error in packaging, and warning in installing scripts.

2021-05-19 02:48 UTC, zitsen reviewed
All things done.

2021-05-19 03:17 UTC, sangshuduo approved these changes

2021-05-19 03:17 UTC, merged