修复windows下vscode调试go程序名无后缀的情况导致程序crash
taosdata/TDengine pull request #6176
Opened 2021-05-20 09:04 UTC by yaofei517

2021-05-20 09:05 UTC, yaofei517 commented
调试通过

2021-05-20 09:30 UTC, zitsen commented on src/os/src/windows/wSemphone.c
> +  if(sub!=NULL){
Thanks, please use consist format style with other codes.

```c
char* sub = strchr(filepath, '.');
if (sub != null) {
  *sub  = '\0';
}
```

2021-05-21 01:48 UTC, sangshuduo commented
wSemphone.c

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(103): error C2220: warning treated as error - no 'object' file generated

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(103): warning C4005: 'AF\_IPX': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(457): note: see previous definition of 'AF\_IPX'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(147): warning C4005: 'AF\_MAX': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(476): note: see previous definition of 'AF\_MAX'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(185): warning C4005: 'SO\_DONTLINGER': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(399): note: see previous definition of 'SO\_DONTLINGER'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(238): error C2011: 'sockaddr': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(482): note: see declaration of 'sockaddr'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(440): error C2059: syntax error: 'constant'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(575): warning C4005: 'IN\_CLASSA': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(284): note: see previous definition of 'IN\_CLASSA'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(581): warning C4005: 'IN\_CLASSB': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(290): note: see previous definition of 'IN\_CLASSB'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(587): warning C4005: 'IN\_CLASSC': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(296): note: see previous definition of 'IN\_CLASSC'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(598): warning C4005: 'INADDR\_ANY': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(301): note: see previous definition of 'INADDR\_ANY'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(600): warning C4005: 'INADDR\_BROADCAST': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(303): note: see previous definition of 'INADDR\_BROADCAST'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\\ws2def.h(636): error C2011: 'sockaddr\_in': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(309): note: see declaration of 'sockaddr\_in'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(136): error C2011: 'fd\_set': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(65): note: see declaration of 'fd\_set'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(156): warning C4005: 'FD\_CLR': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(94): note: see previous definition of 'FD\_CLR'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(171): warning C4005: 'FD\_SET': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(99): note: see previous definition of 'FD\_SET'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(180): error C2011: 'timeval': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(108): note: see declaration of 'timeval'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(236): error C2011: 'hostent': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(164): note: see declaration of 'hostent'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(249): error C2011: 'netent': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(177): note: see declaration of 'netent'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(256): error C2011: 'servent': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(184): note: see declaration of 'servent'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(268): error C2011: 'protoent': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(196): note: see declaration of 'protoent'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(364): error C2011: 'WSAData': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(319): note: see declaration of 'WSAData'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(462): error C2011: 'sockproto': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(491): note: see declaration of 'sockproto'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(504): error C2011: 'linger': 'struct' type redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(528): note: see declaration of 'linger'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(517): warning C4005: 'SOMAXCONN': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(541): note: see previous definition of 'SOMAXCONN'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(552): warning C4005: 'FD\_READ': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(559): note: see previous definition of 'FD\_READ'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(555): warning C4005: 'FD\_WRITE': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(560): note: see previous definition of 'FD\_WRITE'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(558): warning C4005: 'FD\_OOB': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(561): note: see previous definition of 'FD\_OOB'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(561): warning C4005: 'FD\_ACCEPT': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(562): note: see previous definition of 'FD\_ACCEPT'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(564): warning C4005: 'FD\_CONNECT': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(563): note: see previous definition of 'FD\_CONNECT'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(567): warning C4005: 'FD\_CLOSE': macro redefinition

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(564): note: see previous definition of 'FD\_CLOSE'

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock2.h(1625): error C2375: 'accept': redefinition; different linkage

C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\\winsock.h(739): note: see d [...]

2021-05-21 02:12 UTC, sangshuduo requested changes
please fix compile error.

2021-05-23 09:11 UTC, merged

2021-05-23 09:13 UTC, sangshuduo commented
@yaofei517  thanks for your contribution.

2021-05-23 14:43 UTC, yu285 commented
您好，我是涛思数据的工作人员，方便留一下联系方式吗？可以拉您进我们的贡献者群，和大家一起交流技术。

2021-05-24 00:41 UTC, yaofei517 commented
> 您好，我是涛思数据的工作人员，方便留一下联系方式吗？可以拉您进我们的贡献者群，和大家一起交流技术。
好的，微信：huanliu517 请拉我进群