Test/td 5369
taosdata/TDengine pull request #6984
Opened 2021-07-22 12:11 UTC by wenzhouwww

commit test case for taosdemo about nano support !

in this case , the sql file is must be here !

2021-07-23 02:50 UTC, xiaopingcs requested changes
建议PR的标题也要按照commit规则来写： https://jira.taosdata.com:18090/pages/viewpage.action?pageId=16417585

2021-07-23 02:50 UTC, xiaopingcs commented on tests/pytest/fulltest.sh
> +python3 test.py -f  tools/taosdemoAllTest/pytest.py
Jenkins 跑python测试分为4部分并行跑，你放到p4-end外面，这个应该不会被测试到，需要加到p4-end里面。而且需要注意的是每一部分的测试时间设置的是45分钟，超时会报错，Jenkins运行失败，所以添加的case运行时间不要太长。

2021-07-23 02:50 UTC, xiaopingcs commented on tests/pytest/tools/taosdemoAllTest/taosdemoTestNanoCreateDB.sql
> +INSERT INTO d1001 USING METERS TAGS ("Beijng.Chaoyang", 2) VALUES (now, 85, 32, 0.76);
这个文件只被使用了一次，感觉没有必要单独建一个文件，可以直接写到测试例里面

2021-07-23 02:50 UTC, xiaopingcs commented on tests/pytest/tools/taosdemoAllTest/taosdemoTestSupportNanoInsert.py
> +
空行太多，建议缩小到1行或2行

2021-07-23 02:53 UTC, wenzhouwww commented on tests/pytest/fulltest.sh
> +python3 test.py -f  tools/taosdemoAllTest/pytest.py
好的，我留意下

2021-07-27 02:02 UTC, liuyq-617 commented on tests/pytest/tools/taosdemoAllTest/taosdemoTestSupportNanoInsert.py
> +        os.system("%staosdemo  -u root -P taosdata -p 6030 -h vm84 -a 1  -m pre -n 10 -T 20 -t 60 -o res.txt -y " % binPath)
不要再case中出现自己的节点名

2021-07-27 02:03 UTC, wenzhouwww commented on tests/pytest/tools/taosdemoAllTest/taosdemoTestSupportNanoInsert.py
> +        os.system("%staosdemo  -u root -P taosdata -p 6030 -h vm84 -a 1  -m pre -n 10 -T 20 -t 60 -o res.txt -y " % binPath)
修改中

2021-07-29 02:28 UTC, merged