Nodejs/xiaolei/td 2979
taosdata/TDengine pull request #7369
Opened 2021-08-14 09:56 UTC by xleili

nodejs test case of 1970

2021-08-14 16:43 UTC, sangshuduo commented on src/connector/nodejs/test/test1970.js
> +console.log(d[i][0].valueOf());
no indent?

2021-08-14 16:43 UTC, sangshuduo commented on src/connector/nodejs/test/test1970.js
> +console.log(d[i][0].valueOf());
no indent?

2021-08-14 16:44 UTC, sangshuduo commented on src/connector/nodejs/test/test1970.js
> +  c1.execute("insert into "+dbname+"."+tbname+" values(-1,13)");
why indent?

2021-08-14 16:44 UTC, sangshuduo commented on src/connector/nodejs/test/test1970.js
> +  c1.execute("insert into "+dbname+"."+tbname+" values('1970-01-01 07:59:59.999',3)");
why indent?

2021-08-16 02:40 UTC, xleili reviewed
ident fixed

2021-08-20 02:48 UTC, zitsen approved these changes

2021-08-20 02:48 UTC, zitsen commented on src/connector/nodejs/test/test1970.js
> +
better to use like this:

```js
let sql = '';
console.log(sql);
c1.execute(sql);
```

2021-08-20 02:48 UTC, zitsen commented on src/connector/nodejs/test/test1970.js
> +    console.log(d[i][0].valueOf());
indent by 2 space across the nodejs project.

2021-08-20 06:03 UTC, sangshuduo commented on src/connector/nodejs/test/test1970.js
> +
yes, that's DRY (Don't Repeast Yourself) principle. @xleili

2021-08-20 11:40 UTC, xleili commented on src/connector/nodejs/test/test1970.js
> +
thank you. I got it.

2021-08-20 11:58 UTC, sangshuduo requested changes
need to apply DRY principle

2021-08-24 10:56 UTC, xleili reviewed
applied dry principle

2021-08-24 11:25 UTC, sangshuduo approved these changes
LGTM

2021-08-24 11:37 UTC, xleili reviewed
add ci

2021-08-31 16:16 UTC, merged