Feature/xiaolei/td 1860 node restful
taosdata/TDengine pull request #7900
Opened 2021-09-13 11:31 UTC by xleili

pr commit test，skip this till formal commit

2021-09-13 11:37 UTC, sangshuduo requested changes
test program need check result.

2021-09-13 13:11 UTC, zitsen requested changes
Try to build a better node project from scratch.

2021-09-13 13:11 UTC, zitsen commented on src/connector/node-rest/src/restResult.js
> +    this._init(jason)
What is `jason` mean

2021-09-13 13:11 UTC, zitsen commented on src/connector/node-rest/src/restResult.js
> +  _suggestedMinWidths = {
move it to const variable out of the class.

2021-09-13 13:11 UTC, zitsen commented on src/connector/node-rest/test/testRestConn.js
> +})()
async function may runs after next row, please fix the order.

2021-09-23 02:54 UTC, xleili reviewed
fix test,ci,and async order

2021-09-24 02:09 UTC, sangshuduo approved these changes
LGTM

2021-09-24 02:09 UTC, merged