[td-10748]interp
taosdata/TDengine pull request #8590
Opened 2021-11-05 08:48 UTC by dapan1121

2021-11-16 02:16 UTC, shenglian-zhou commented on src/query/src/qExecutor.c
> +      assert(pOperator->upstream[0]->notify == NULL);
did not find the location where notify is set to NULL

2021-11-18 02:26 UTC, hjxilinx requested changes

2021-11-18 02:26 UTC, hjxilinx commented on src/inc/taosmsg.h
> +  STimeWindow range;
Could you please add a little bit more comment on this attribute to explain why this attribute is needed?

2021-11-18 03:10 UTC, dapan1121 commented on src/inc/taosmsg.h
> +  STimeWindow range;
ok

2021-11-18 05:59 UTC, hjxilinx approved these changes
I'm OK with this PR.

2021-11-18 09:31 UTC, shenglian-zhou commented on src/query/src/qFill.c
>    GET_TYPED_DATA(v1, double, inputType, point1->val);
for integer values, keep double calculation at the last step and as much as integer calculation as possible?

2021-11-18 10:04 UTC, dapan1121 commented on src/query/src/qFill.c
>    GET_TYPED_DATA(v1, double, inputType, point1->val);
好像意义不是很大，既然运算过程中肯定要 double保持精度，那就必然有需要转到double的部分。

2021-11-19 00:26 UTC, merged