[TD-10897]<fix>: SchemaLess : Schemaless will auto convert Convert uppercase letters to lowercase
taosdata/TDengine pull request #8703
Opened 2021-11-16 09:11 UTC by glzhao89

2021-11-18 08:46 UTC, dapan1121 requested changes

2021-11-18 08:46 UTC, dapan1121 commented on src/client/src/tscParseLineProtocol.c
> +    memcpy(tableNameBuf, tableName, strlen(tableName));
这里没有初始化tableNameBuf，直接memcpy的结果是没有结束符的，tGetToken中对tableNameBuf的使用就可能是不安全的

2021-11-18 08:59 UTC, shenglian-zhou approved these changes
face-2-face reviewed

2021-11-23 07:15 UTC, dapan1121 approved these changes

2021-11-23 07:15 UTC, merged