[TD-10797]<fix>: when column length is long, report 'invalid column name' error
taosdata/TDengine pull request #8774
Opened 2021-11-23 06:02 UTC by glzhao89

2021-11-23 07:33 UTC, dapan1121 requested changes

2021-11-23 07:33 UTC, dapan1121 commented on src/client/src/tscSQLParser.c
> +  const char* msg8 = "invalid column name length";
建议统一一下错误提示信息就不需要再加新的错误吗了

2021-11-23 08:15 UTC, glzhao89 commented on src/client/src/tscSQLParser.c
> +  const char* msg8 = "invalid column name length";
已将信息统一改为“invalid xx name or length” 就不再多添加新错误码了

2021-11-23 08:35 UTC, winshining approved these changes
Looks good to me.

2021-11-25 05:31 UTC, dapan1121 approved these changes

2021-11-25 05:31 UTC, merged