[TS-653]<fix>: forbidden count(tbname) to mix up with agg, proj etc.
taosdata/TDengine pull request #8778
Opened 2021-11-23 11:37 UTC by stephenkgu

2021-11-23 11:45 UTC, guanshengliang approved these changes

2021-11-23 11:46 UTC, guanshengliang commented
LGTM

2021-11-24 07:39 UTC, dapan1121 requested changes

2021-11-24 07:39 UTC, dapan1121 commented on src/client/src/tscSQLParser.c
> +  if (countTbname && (prjNum > 0 || aggNum > 0 || scalarUdf > 0)) {
1. aggUdf也不能共存 2.count(tag)跟count(tbname)应该是同样的规则，一起改了呗

2021-11-27 08:01 UTC, stephenkgu commented on src/client/src/tscSQLParser.c
> +  if (countTbname && (prjNum > 0 || aggNum > 0 || scalarUdf > 0)) {
added aggUdf, please review again.

2021-11-29 10:47 UTC, dapan1121 approved these changes

2021-11-29 10:50 UTC, merged