modify getting start
taosdata/TDengine pull request #8929
Opened 2021-12-04 08:11 UTC by boxiaobj

Add preinstallation notes

2021-12-06 03:13 UTC, tomchon approved these changes
LGTM，经常有人问update的这个事情，是否需要在这里多提一句

2022-01-06 01:51 UTC, plum-lihui reviewed
“目前TDengine服务端仅支持Linux X64系统”： 这个描述不正确吧，我们还支持aarch32呢，应该是还支持arm 32bit的系统。

2022-03-03 02:04 UTC, dingbo8128 commented
如果确定改的不对， 要不要关掉这个 pr ？ @boxiaobj

2022-03-03 05:58 UTC, sangshuduo requested changes
This topic should be put in another position.

2022-03-03 05:58 UTC, closed without merging