fix: change strcpy to tstrncpy
taosdata/TDengine pull request #9050
Opened 2021-12-12 13:03 UTC by tiantian001

2021-12-16 02:47 UTC, wangmm0220 approved these changes

2021-12-16 06:19 UTC, wangmm0220 requested changes

2021-12-16 06:19 UTC, wangmm0220 commented on src/util/src/tnettest.c
> +  tstrncpy(reqMsg.pCont, "nettest", sizeof(reqMsg.pCont));
There are two problems.
The first: reqMsg.pCont is void *, so sizeof(reqMsg.pCont)=4(32-bit machine) or 8(64-bit machine)
The second: Expand tstrncpy, we will get reqMsg.pCont[size-1] = 0. but reqMsg.pCont is void *, this means we can not know the type of  reqMsg.pCont, so  it is error.

The right is : tstrncpy((char*)reqMsg.pCont, "nettest", pkgLen);   or you can leave this line alone, it is ok. Because pkgLen if long than strlen("nettest").

2021-12-16 06:19 UTC, wangmm0220 commented on src/util/src/tnettest.c
> +    tstrncpy(reqMsg.pCont, "nettest speed", sizeof(reqMsg.pCont));
There are two problems.
The first: reqMsg.pCont is void *, so sizeof(reqMsg.pCont)=4(32-bit machine) or 8(64-bit machine)
The second: Expand tstrncpy, we will get reqMsg.pCont[size-1] = 0. but reqMsg.pCont is void *, this means we can not know the type of  reqMsg.pCont, so  it is error.

The right is : tstrncpy((char*)reqMsg.pCont, "nettest speed", pkgLen);   or you can leave this line alone, it is ok. Because pkgLen if long than strlen("nettest speed").

2021-12-16 07:31 UTC, wangmm0220 approved these changes

2021-12-17 02:01 UTC, guanshengliang approved these changes

2021-12-17 02:01 UTC, merged