Feature/xiaolei/td 10546 nodejs json tag
taosdata/TDengine pull request #9066
Opened 2021-12-13 09:36 UTC by xleili

2021-12-17 02:09 UTC, zitsen requested changes
Please update.

2021-12-17 02:09 UTC, zitsen commented on src/connector/nodejs/nodetaos/cinterface.js
> +
Unnecessary multiple empty lines. Use single empty line between code blocks.

2021-12-17 02:09 UTC, zitsen commented on src/connector/nodejs/nodetaos/cinterface.js
> +TaosField.defineProperty('bytes', ref.types.uint16);
`bytes` type is int16. See C struct:

```c
typedef struct taosField {
  char     name[65];
  uint8_t  type;
  int16_t  bytes;
} TAOS_FIELD;
```

2021-12-17 03:15 UTC, xleili commented on src/connector/nodejs/nodetaos/cinterface.js
> +
done

2021-12-17 03:15 UTC, xleili commented on src/connector/nodejs/nodetaos/cinterface.js
> +TaosField.defineProperty('bytes', ref.types.uint16);
done

2021-12-18 04:49 UTC, zitsen approved these changes
LGTM.

2021-12-19 03:38 UTC, sangshuduo approved these changes
LGTM

2021-12-19 03:38 UTC, merged