[TD-10547]<feature>:c# support json tag
taosdata/TDengine pull request #9069
Opened 2021-12-13 10:20 UTC by xleili

2021-12-18 14:03 UTC, sangshuduo approved these changes
LGTM

2021-12-20 05:55 UTC, zitsen requested changes

2021-12-20 05:55 UTC, zitsen commented on .gitignore
> +src/connector/C#/src/TDengineDriver/bin/
Add .gitignore file in its directory.

2021-12-20 06:26 UTC, zitsen approved these changes
LGTM

2021-12-21 02:49 UTC, merged