[TD-12102]<fix>:csharp support fetch_lengths,fix fetch_row binray ret…
taosdata/TDengine pull request #9107
Opened 2021-12-15 11:03 UTC by xleili

…rieve error

2021-12-16 06:30 UTC, sangshuduo approved these changes
LGTM

2021-12-20 05:49 UTC, zitsen requested changes
Please update.

2021-12-20 05:49 UTC, zitsen commented on src/connector/C#/src/TDengineDriver/TDengineDriver.cs
> +        static extern public IntPtr FetchLength(IntPtr taos);
Make the name comparable. FetchLength -> FetchLengths.

2021-12-20 05:49 UTC, zitsen commented on src/connector/C#/src/test/Cases/FetchLength.cs
> +            UtilsTools.DisplayRes(res);
Compare the data to expected in test case, not only display.

2021-12-20 05:51 UTC, xleili commented on src/connector/C#/src/test/Cases/FetchLength.cs
> +            UtilsTools.DisplayRes(res);
I'will fix, and update this test case later.

2021-12-20 05:51 UTC, xleili commented on src/connector/C#/src/TDengineDriver/TDengineDriver.cs
> +        static extern public IntPtr FetchLength(IntPtr taos);
ok, i will fix it

2021-12-20 09:16 UTC, xleili commented on src/connector/C#/src/TDengineDriver/TDengineDriver.cs
> +        static extern public IntPtr FetchLength(IntPtr taos);
done

2021-12-20 09:16 UTC, xleili commented on src/connector/C#/src/test/Cases/FetchLength.cs
> +            UtilsTools.DisplayRes(res);
done

2021-12-20 10:08 UTC, zitsen approved these changes
LGTM

2021-12-23 03:46 UTC, merged