[TS-819]<fix>: windows negative timestamp error.
taosdata/TDengine pull request #9229
Opened 2021-12-20 17:11 UTC by afwerar

2021-12-21 02:39 UTC, sangshuduo commented on src/kit/shell/src/shellEngine.c
> +    } else {
```
suggestion:
if (nanosec)
   process_nanosecond
else if (microsec)
   process_microsec
else if (millisec)
   process_millisec
else
   prompt error
```

2021-12-21 02:39 UTC, sangshuduo commented on src/kit/shell/src/shellEngine.c
> +    SYSTEMTIME a={1970,1,5,1,0,0,0,0}; // support 1601-01-01 00:00:00
confused why comment is 1601 but variable is 1970

2021-12-22 02:37 UTC, sangshuduo requested changes

2021-12-22 02:37 UTC, sangshuduo commented on src/kit/shell/src/shellEngine.c
> +    SYSTEMTIME a={1970,1,5,1,0,0,0,0}; // support 1601-01-01 00:00:00
SYSTEMTIME struct support 1601-01-01. set 1970 to compatible with Epoch time

2021-12-22 02:44 UTC, sangshuduo approved these changes
LGTM

2021-12-22 03:34 UTC, stephenkgu approved these changes

2021-12-23 02:37 UTC, merged