[TD-12520]<docs>: refine docker documents.
taosdata/TDengine pull request #9395
Opened 2021-12-26 08:18 UTC by sangshuduo

2021-12-26 08:56 UTC, boxiaobj approved these changes
建议把访问容器中的taosAdapter+taosd的启动命令行给出来，减少用户的出错机会。

2021-12-26 10:21 UTC, sangshuduo commented
> 建议把访问容器中的taosAdapter+taosd的启动命令行给出来，减少用户的出错机会。

OK，我在 2.4.0.0 发布到正确的 channel 之后增加 taosAdapter 相关的段落

2021-12-28 05:29 UTC, jtao1735 requested changes

2021-12-28 05:29 UTC, jtao1735 commented on documentation20/cn/02.getting-started/01.docker/docs.md
> +### 在 Docker 容器中运行 TDengine server 用于开发验证（不对容器外部提供服务）
”不对容器外部提供服务“是不是有点多余？ 应该与下面的”对容器外提供服务“进行合并，只是-p作为一个选项，说明一下

2021-12-28 05:52 UTC, sangshuduo commented on documentation20/cn/02.getting-started/01.docker/docs.md
> +### 在 Docker 容器中运行 TDengine server 用于开发验证（不对容器外部提供服务）
OK

2021-12-28 09:47 UTC, sangshuduo commented on documentation20/cn/02.getting-started/01.docker/docs.md
> +### 在 Docker 容器中运行 TDengine server 用于开发验证（不对容器外部提供服务）
已修正，并增加 taosAdapter 相关容器使用说明

2021-12-29 21:50 UTC, jtao1735 commented on documentation20/cn/02.getting-started/01.docker/docs.md
> +### 在 Docker 容器中运行 TDengine server 用于开发验证（不对容器外部提供服务）
OK

2021-12-29 21:50 UTC, jtao1735 approved these changes

2021-12-30 10:44 UTC, merged