[TD-12534](connector)<enchance>:scharp connector publish to nuget
taosdata/TDengine pull request #9444
Opened 2021-12-28 09:06 UTC by xleili

2021-12-29 03:59 UTC, sangshuduo commented on src/connector/C#/src/TDengineDriver/TDengineDriver.csproj
> +    <PackageTags>Taos;Data;Microsoft.NET.Sdk;Iot;bigdata;TDengine;taosdata</PackageTags>
IoT or IOT

2021-12-29 04:00 UTC, sangshuduo commented on src/connector/C#/src/TDengineDriver/TDengineDriver.csproj
> +        more information please vist:https://www.taosdata.com
visit

2021-12-29 04:01 UTC, sangshuduo requested changes
see my comments

2021-12-29 04:13 UTC, zitsen requested changes
Please update.

2021-12-29 04:13 UTC, zitsen commented on src/connector/C#/src/TDengineDriver/TDengineDriver.csproj
> +        more information please vist:https://www.taosdata.com
`:https` to `: https`, add space between url and others

2021-12-29 04:13 UTC, zitsen commented on tests/examples/C#/stmt/StmtDemo.cs
> +            // stmtDemo.loadTableInfo(tableList);
Does this cause error if uncommented?

2021-12-29 05:48 UTC, xleili commented on tests/examples/C#/stmt/StmtDemo.cs
> +            // stmtDemo.loadTableInfo(tableList);
执行查询前调用loadTableInfo，会导致select出来的结果为空。所以我注释掉了

2021-12-29 05:49 UTC, xleili commented on src/connector/C#/src/TDengineDriver/TDengineDriver.csproj
> +        more information please vist:https://www.taosdata.com
ok

2021-12-29 05:49 UTC, xleili commented on src/connector/C#/src/TDengineDriver/TDengineDriver.csproj
> +    <PackageTags>Taos;Data;Microsoft.NET.Sdk;Iot;bigdata;TDengine;taosdata</PackageTags>
ok

2021-12-29 06:01 UTC, sangshuduo approved these changes
LGTM

2021-12-30 08:51 UTC, zitsen approved these changes
LGTM

2021-12-30 09:51 UTC, merged