[TD-11773]<feature>(tools): taosbenchmark support taosadapter
taosdata/TDengine pull request #9861
Opened 2022-01-17 11:41 UTC by zhaoyanggh

2022-01-17 11:45 UTC, sangshuduo commented on tests/develop-test/5-taos-tools/taosbenchmark/json/rest_auto_create_table.json
> +  "thread_count": 1,
how about using multithread?

2022-01-17 11:45 UTC, sangshuduo commented on tests/develop-test/5-taos-tools/taosbenchmark/json/sml_auto_create_table.json
> +  "thread_count": 1,
how about using multithread?

2022-01-17 11:45 UTC, sangshuduo commented on tests/develop-test/5-taos-tools/taosbenchmark/json/sml_insert_alltypes.json
> +  "thread_count": 1,
same question

2022-01-17 11:45 UTC, sangshuduo commented on tests/develop-test/5-taos-tools/taosbenchmark/json/sml_json_alltypes.json
> +  "thread_count": 1,
same question

2022-01-17 11:46 UTC, sangshuduo requested changes
see my comments. And 2.4 needs a PR too.

2022-01-17 14:18 UTC, afwerar approved these changes
LGTM

2022-01-18 05:56 UTC, sangshuduo approved these changes
LGTM

2022-01-18 05:56 UTC, merged