[TD-13119]<docs>:csharp connector add readme
taosdata/TDengine pull request #9930
Opened 2022-01-20 09:21 UTC by xleili

2022-01-20 09:45 UTC, sangshuduo commented on src/connector/C#/README.md
> +* The C # connector supports: Linux 64/Windows x64/Windows x86.
C#, not 'C #'

2022-01-20 09:46 UTC, sangshuduo commented on src/connector/C#/README.md
> +* C# connector can be download and include as normal table form [Nuget.org](https://www.nuget.org/packages/TDengine.Connector/).
downloaded, included

2022-01-20 09:47 UTC, sangshuduo commented on src/connector/C#/README.md
> +* .NET interface file TDengineDrivercs.cs and reference sample TDengineTest.cs
TDengineDrivercs.cs ?

2022-01-20 09:53 UTC, zitsen requested changes
See my comments

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +* .NET interface file TDengineDrivercs.cs and reference sample TDengineTest.cs
`TDengineDrivercs` you mean `TDengineDriver`?

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +Need install .Net SDK first
if this is new paragraph, finish previous paragraph with `.`, and add a break line.

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +cd {client_install_directory}/examples/C#/C#Checker
`#` may cause error, use `\#` or "<path>" style.

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> + * Defualt: charset,locale,timezone same to system.
Default.

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +TDengine.Options((int)TDengineInitOption.TDDB_OPTION_CONFIGDIR,configDir);
TDDB ?-> TSDB

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +// Recommand to clean environment, before exit the your application.
Recommand -> Recommend

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +         // Execute query sql faild
faild -> failed

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +    // Feild count, num of field, that is equal to retrieved column number
Feild -> Field

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +    // Getting querying result's feild info as a List.
feild -> field

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +    // Traverse data from retreive result
retreive -> retrieve

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +// need to free the allocated ummanaged memory.
ummanaged -> unmanaged

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +// Tthis "result" cam be traversed as normal sql query result.
Tthis -> This

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +// Free result,free the restsult.
restsult -> result

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +* Assert (samples about how to assert every step of stmt is successed or not)
is successed -> has succeeded or is success

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +// Specail StmtInit().
Special?

2022-01-20 09:53 UTC, zitsen commented on src/connector/C#/README.md
> +so when. NET project generates a .exe file, please select the correspond
line breaks in list should be indented:

```markdown
* a long long long long 
  indented next line.
* text two
```

2022-01-20 12:26 UTC, xleili commented on src/connector/C#/README.md
> +* The C # connector supports: Linux 64/Windows x64/Windows x86.
fixed

2022-01-20 12:34 UTC, xleili commented on src/connector/C#/README.md
> +so when. NET project generates a .exe file, please select the correspond
great！

2022-01-20 12:49 UTC, sangshuduo commented on src/connector/C#/README.md
> +* This C# connector can be downloaded and included as a normal package form [Nuget.org](https://www.nuget.org/packages/TDengine.Connector/).
from...

2022-01-20 12:50 UTC, sangshuduo commented on src/connector/C#/README.md
> +You can find examples under follow directions:
directories?

2022-01-20 12:54 UTC, zitsen commented on src/connector/C#/README.md
> +* Install TDengine client, please refers to the[steps of installing connector driver](https://www.taosdata.com/en/documentation/connector#driver).
leave a space after the

2022-01-20 12:56 UTC, zitsen commented on src/connector/C#/README.md
> +* .NET interface file TDengineDriver.cs and reference samples both
remove *reference*

2022-01-20 12:58 UTC, zitsen commented on src/connector/C#/README.md
> +Need to install .Net SDK first.
.NET SDK is instructed in Installation preparations section, so this line is not necessary.

2022-01-20 12:59 UTC, zitsen commented on src/connector/C#/README.md
> +connect,query and so on.
leave a space after `,` .

2022-01-20 13:00 UTC, zitsen commented on src/connector/C#/README.md
> +* Create a dotnet project. (Using console project as an example.)
Create a dotnet project (using ...).

2022-01-20 13:02 UTC, zitsen commented on src/connector/C#/README.md
> +  and other VS versions have not being verified yet.
1. no `and`
2. have not being -> have not been

2022-01-20 13:03 UTC, zitsen commented on src/connector/C#/README.md
> +* TDengine V2.0. 3.0 supports both 32-bit and 64-bit Windows systems,
remove the space in version string:

`V2.0. 3.0` -> `V2.0.3.0`

2022-01-20 13:06 UTC, sangshuduo reviewed
see my comments

2022-01-21 03:32 UTC, sangshuduo approved these changes
LGTM

2022-01-21 09:08 UTC, zitsen approved these changes
LGTM

2022-01-21 09:14 UTC, merged